# Generated by Django 5.2.12 on 2026-05-08 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=150, verbose_name='Nome do proprietário')),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=2)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='distribuidora',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.farmacia'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.farmacia'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.farmacia'),
        ),
        migrations.AddField(
            model_name='produtodiverso',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.farmacia'),
        ),
    ]
